Repository substrate-developer-hub/substrate-docs, pull requests merged in 2021-10, with the labels that each got.

#214 frontier patch
  v3/tutorials/10-frontier-workshop/index.mdx
Labels: documentation, trivial

#224 Feedback Widget Setup
  src/components/Buttons/SecondaryButton.tsx
  src/components/DocsComponents/FeedbackWidget.tsx
  src/components/DocsComponents/index.tsx
  src/components/Icon.tsx
  src/components/SEO.tsx
  src/images/svgs/feedback-icon.svg
  src/templates/htg-template.tsx
  src/templates/kb-template.tsx
  src/templates/tut-template.tsx
Labels: web-dev

#203 Cumulus Tutorial Refactor & Update
  .env.development
  .prettierignore
  gatsby-config.js
  gatsby-node.js
  src/components/DevNavMenu.tsx
  src/components/DocsNavMobile.tsx
  src/images/tutorials/09-cumulus/crowdloan-contribute.png
  src/images/tutorials/09-cumulus/crowdloan-success.png
  src/images/tutorials/09-cumulus/crowdloan-sucess.png
  src/images/tutorials/09-cumulus/favicon.png
  src/images/tutorials/09-cumulus/forceLease.png
  src/images/tutorials/09-cumulus/parachain-active-lease.png
  src/images/tutorials/09-cumulus/parachain-bid.png
  src/images/tutorials/09-cumulus/parachain-crowdloan.png
  src/images/tutorials/09-cumulus/parachain-registration-sudo.png
  src/images/tutorials/09-cumulus/parachain-summary-screenshot.png
  src/images/tutorials/09-cumulus/parachains.png
  src/images/tutorials/09-cumulus/paraid-reserve.png
  src/images/tutorials/09-cumulus/parathread-onboarding.png
  src/images/tutorials/09-cumulus/parathread-register-success.png
  src/images/tutorials/09-cumulus/parathread-register.png
  src/images/tutorials/09-cumulus/polkadot-apps-with-2-parachains.png
  src/images/tutorials/09-cumulus/polkadot-launch-log.png
  src/images/tutorials/09-cumulus/register-parathread.png
  src/images/tutorials/09-cumulus/session-keys.png
  src/pages/tutorials/v3.tsx
  static/_redirects
  static/assets/tutorials/cumulus-workshop/node-start-local-testing.sh
  static/assets/tutorials/cumulus/chainspecs/rococo-custom-2-plain.json
  static/assets/tutorials/cumulus/chainspecs/rococo-custom-2-raw.json
  static/assets/tutorials/cumulus/chainspecs/rococo-custom-3-plain.json
  static/assets/tutorials/cumulus/chainspecs/rococo-custom-3-raw.json
  static/assets/tutorials/cumulus/chainspecs/rococo-custom-4-plain.json
  static/assets/tutorials/cumulus/chainspecs/rococo-custom-4-raw.json
  static/assets/tutorials/cumulus/chainspecs/snippets-to-copy.md
  static/assets/tutorials/cumulus/node-start-local-testing.sh
  static/assets/tutorials/cumulus/polkadot-launch-config/relay-3-validators--2paras-1collator.json
  v3/how-to-guides/07-parachains/c-reserve-id/index.mdx
  v3/how-to-guides/07-parachains/d-register/index.mdx
  v3/how-to-guides/07-parachains/e-start-collator-node/index.mdx
  v3/how-to-guides/07-parachains/f-start-testnet/index.mdx
  v3/tutorials/09-cumulus-workshop/a-getting-started/index.mdx
  v3/tutorials/09-cumulus-workshop/c-polkadot-launch/index.mdx
  v3/tutorials/09-cumulus/a-start-relay/index.mdx
  v3/tutorials/09-cumulus/b-connecting-to-relay/index.mdx
  v3/tutorials/09-cumulus/c-polkadot-launch/index.mdx
  v3/tutorials/09-cumulus/d-rococo/index.mdx
Labels: documentation, devhub

#250 Update parachain runtime upgrades HTG
  gatsby-node.js
  i18n/react-intl/en.json
  src/components/DevNavMenu.tsx
  src/pages/tutorials/v3.tsx
  v3/how-to-guides/07-parachains/a-preparing/index.mdx
  v3/how-to-guides/07-parachains/a-runtime-upgrades/index.mdx
Labels: devhub, how-to-guide

#449 WIP - Gatsby Node Updates
  gatsby-config.js
  gatsby-node.js
  src/components/DevNavMenu.tsx
  src/components/DocsComponents/NextButton.tsx
  src/components/DocsNav.tsx
  src/components/DocsNavMobile.tsx
  src/templates/doc-template.tsx
  src/templates/htg-template.tsx
  src/templates/tut-template.tsx
  v3/tutorials/01-create-your-first-substrate-chain/index.mdx
  v3/tutorials/02-proof-of-existence/index.mdx
  v3/tutorials/03-permissioned-network/index.mdx
  v3/tutorials/04-forkless-upgrades/index.mdx
  v3/tutorials/05-private-network/index.mdx
  v3/tutorials/06-node-metrics/index.mdx
  v3/tutorials/07-add-a-pallet/index.mdx
  v3/tutorials/08-ink-workshop/a-getting-started/index.mdx
  v3/tutorials/08-ink-workshop/b-develop-smart-contract/index.mdx
  v3/tutorials/08-ink-workshop/c-build-erc20-contract/index.mdx
  v3/tutorials/09-cumulus/a-start-relay/index.mdx
  v3/tutorials/09-cumulus/b-connecting-to-relay/index.mdx
  v3/tutorials/09-cumulus/c-polkadot-launch/index.mdx
  v3/tutorials/09-cumulus/d-rococo/index.mdx
  v3/tutorials/10-frontier-workshop/index.mdx
  v3/tutorials/11-kitties-workshop/a-kitties-node/index.mdx
  v3/tutorials/11-kitties-workshop/b-kitties-frontend/index.mdx
Labels: ⛔ DO NOT MERGE ⛔, MIGHT_BREAK_THINGS ⚠️

#369 [docs] Rework Add Contracts Pallet
  src/styles/language-tabs.css
  v3/how-to-guides/02-pallet-design/a-add-contracts-pallet/index.mdx
Labels: doc 📚, how-to guide 🔢

#404 [docs] Randomness rework
  v3/how-to-guides/02-pallet-design/c-randomness/index.mdx
Labels: doc 📚, how-to guide 🔢
