Repository substrate-developer-hub/substrate-docs, pull requests merged in 2021-11, with the labels that each got.

#490 [docs] fix small typo issue 474
  v3/docs/03-runtime/b-macros/index.mdx
Labels: bug 🐛

#469 Update to Polkadot `0.9.11` and parse tutorial into two new HTGs
  gatsby-node.js
  src/pages/tutorials/v3.tsx
  static/assets/tutorials/cumulus/chain-specs/rococo-custom-3-plain.json
  static/assets/tutorials/cumulus/chain-specs/rococo-custom-3-raw.json
  static/assets/tutorials/cumulus/chain-specs/rococo-custom-4-plain.json
  static/assets/tutorials/cumulus/chain-specs/rococo-custom-4-raw.json
  v3/how-to-guides/01-basics/e-custom-chainspec/index.mdx
  v3/how-to-guides/07-parachains/a-connect-relay/index.mdx
  v3/how-to-guides/07-parachains/a-solo-to-parachain/index.mdx
  v3/how-to-guides/07-parachains/b-collator-selection/index.mdx
  v3/how-to-guides/07-parachains/c-pre-launch/index.mdx
  v3/how-to-guides/07-parachains/d-runtime-upgrades/index.mdx
  v3/tutorials/09-cumulus/a-start-relay/index.mdx
  v3/tutorials/09-cumulus/b-connecting-to-relay/index.mdx
  v3/tutorials/09-cumulus/c-polkadot-launch/index.mdx
  v3/tutorials/09-cumulus/d-rococo/index.mdx
Labels: parachains 🌼

#495 rm impl outer macros
  v3/docs/03-runtime/b-macros/index.mdx
Labels: bug 🐛, versioning 🔧

#466 Update ss58 page
  v3/docs/07-advanced/h-ss58/index.mdx
Labels: bug 🐛, rust docs 🦀

#519 fix 505, 440
  .netlify/_redirects_develop
  .netlify/_redirects_production
Labels: broken link ❌

#545 Anchor not working, misses trailing "s"
  v3/docs/01-getting-started/e-glossary/index.mdx
  v3/docs/02-concepts/b-extrinsics/index.mdx
  v3/docs/03-runtime/h-weights-and-fees/index.mdx
Labels: broken link ❌

#544 Replace OG image
  static/img/substrate_og.png
Labels: web-dev 🕸

#553 check link fix
  package.json
Labels: web-dev 🕸

#551 fix formatting
  README.md
  v3/docs/01-getting-started/d-windows-users/index.mdx
  v3/docs/02-concepts/d-transaction-pool/index.mdx
  v3/docs/07-advanced/h-ss58/index.mdx
  v3/how-to-guides/01-basics/a-pallet-integration/index.mdx
  v3/how-to-guides/01-basics/b-instantiable-pallets/index.mdx
  v3/how-to-guides/01-basics/c-constants/index.mdx
  v3/how-to-guides/01-basics/d-genesis-config/index.mdx
  v3/how-to-guides/01-basics/e-custom-chainspec/index.mdx
  v3/how-to-guides/01-basics/e-helper-functions/index.mdx
  v3/how-to-guides/01-basics/f-mint-token/index.mdx
  v3/how-to-guides/01-basics/g-weights/index.mdx
  v3/how-to-guides/02-pallet-design/a-add-contracts-pallet/index.mdx
  v3/how-to-guides/02-pallet-design/b-lockcable-currency/index.mdx
  v3/how-to-guides/02-pallet-design/c-randomness/index.mdx
  v3/how-to-guides/02-pallet-design/d-simple-crowdfund/index.mdx
  v3/how-to-guides/02-pallet-design/e-storage-value/index.mdx
  v3/how-to-guides/02-pallet-design/f-tight-coupling/index.mdx
  v3/how-to-guides/02-pallet-design/g-loose-coupling/index.mdx
  v3/how-to-guides/03-weights/a-calculate-fees/index.mdx
  v3/how-to-guides/03-weights/b-benchmarking/index.mdx
  v3/how-to-guides/03-weights/c-using-benchmark-weights/index.mdx
  v3/how-to-guides/03-weights/d-conditional-weighting-struct/index.mdx
  v3/how-to-guides/04-testing/a-basic-pallet-testing/index.mdx
  v3/how-to-guides/04-testing/b-test-transfer/index.mdx
  v3/how-to-guides/05-storage-migrations/a-nicks-migration/index.mdx
  v3/how-to-guides/05-storage-migrations/b-steps-with-polkadotjs-apps/index.mdx
  v3/how-to-guides/05-storage-migrations/c-migration-tests/index.mdx
  v3/how-to-guides/06-consensus/a-pow/index.mdx
  v3/how-to-guides/06-consensus/b-hybrid-pow-pos/index.mdx
  v3/how-to-guides/08-tools/a-integrate-try-runtime/index.mdx
  v3/how-to-guides/08-tools/b-txwrapper/index.mdx
  v3/tutorials/02-proof-of-existence/index.mdx
  v3/tutorials/11-kitties-workshop/a-kitties-node/index.mdx
  v3/tutorials/11-kitties-workshop/b-kitties-frontend/index.mdx
Labels: web-dev 🕸, team internal 👨‍👩‍👦‍👦

#589 Cumulus updates and new content
  i18n/react-intl/en.json
  src/components/DevNavMenu.tsx
  v3/how-to-guides/07-parachains/a-solo-to-parachain/index.mdx
  v3/tutorials/09-cumulus/a-start-relay/index.mdx
  v3/tutorials/09-cumulus/b-connecting-to-relay/index.mdx
  v3/tutorials/09-cumulus/c-polkadot-launch/index.mdx
  v3/tutorials/09-cumulus/d-rococo/index.mdx
Labels: new content 💡✍️, parachains 🌼
