Repository substrate-developer-hub/substrate-docs, pull requests merged in 2022-02, with the labels that each got.

#801 [WIP] Update to `polkadot-v0.9.16`
  static/assets/tutorials/cumulus/chain-specs/rococo-custom-2-plain.json
  static/assets/tutorials/cumulus/chain-specs/rococo-custom-2-raw.json
  static/assets/tutorials/cumulus/node-start-local-testing.sh
  v3/how-to-guides/01-basics/e-custom-chainspec/index.mdx
  v3/tutorials/09-cumulus/a-start-relay/index.mdx
  v3/tutorials/09-cumulus/b-connecting-to-relay/index.mdx
  v3/tutorials/09-cumulus/c-polkadot-launch/index.mdx
  v3/tutorials/09-cumulus/d-rococo/index.mdx
Labels: parachains 🌼

#806 Newsletter Disclaimer (for ad-blockers)
  src/components/site/Newsletter.js
Labels: web-dev 🕸

#853 Update ink! tutorial for `v3.0.0-rc9`
  static/assets/tutorials/ink-workshop/1.1-finished-code.rs
  static/assets/tutorials/ink-workshop/1.2-finished-code.rs
  static/assets/tutorials/ink-workshop/1.3-finished-code.rs
  static/assets/tutorials/ink-workshop/1.3-template.rs
  static/assets/tutorials/ink-workshop/1.4-finished-code.rs
  static/assets/tutorials/ink-workshop/1.4-template.rs
  static/assets/tutorials/ink-workshop/1.5-finished-code.rs
  static/assets/tutorials/ink-workshop/1.5-template.rs
  static/assets/tutorials/ink-workshop/1.6-finished-code.rs
  static/assets/tutorials/ink-workshop/1.6-template.rs
  static/assets/tutorials/ink-workshop/2.1-finished-code.rs
  static/assets/tutorials/ink-workshop/2.1-template.rs
  static/assets/tutorials/ink-workshop/2.2-finished-code.rs
  static/assets/tutorials/ink-workshop/2.2-template.rs
  static/assets/tutorials/ink-workshop/2.3-finished-code.rs
  static/assets/tutorials/ink-workshop/2.3-template.rs
  static/assets/tutorials/ink-workshop/2.4-finished-code.rs
  static/assets/tutorials/ink-workshop/2.4-template.rs
  v3/tutorials/08-ink-workshop/a-getting-started/index.mdx
  v3/tutorials/08-ink-workshop/b-develop-smart-contract/index.mdx
  v3/tutorials/08-ink-workshop/c-build-erc20-contract/index.mdx
Labels: ink! / contracts / canvas 🖋️
